package com.sap.iot.azure.ref.notification;

import java.util.logging.Level;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ObjectNode;
import com.google.common.annotations.VisibleForTesting;
import com.microsoft.azure.functions.ExecutionContext;
import com.microsoft.azure.functions.annotation.BindingName;
import com.microsoft.azure.functions.annotation.Cardinality;
import com.microsoft.azure.functions.annotation.EventHubTrigger;
import com.microsoft.azure.functions.annotation.FunctionName;
import com.sap.iot.azure.ref.integration.commons.constants.CommonConstants;
import com.sap.iot.azure.ref.integration.commons.context.InvocationContext;
import com.sap.iot.azure.ref.integration.commons.exception.CommonErrorType;
import com.sap.iot.azure.ref.integration.commons.exception.base.IoTRuntimeException;
import com.sap.iot.azure.ref.integration.commons.model.base.eventhub.SystemProperties;
import com.sap.iot.azure.ref.notification.processing.NotificationHandler;
import com.sap.iot.azure.ref.notification.util.Constants;

import java.util.List;
import java.util.Map;

/**
 * Azure function for handling of model change notification payloads generated by model onboarding and
 * mapping applications. These can be Structure, Assignment or Mapping changes.
 */

public class NotificationProcessorFunction {

    private static final ObjectMapper objectMapper = new ObjectMapper();

    private final NotificationHandler notificationHandler;

    public NotificationProcessorFunction() {
        this(new NotificationHandler());
    }

    @VisibleForTesting
    NotificationProcessorFunction(NotificationHandler notificationHandler) {
        this.notificationHandler = notificationHandler;
    }

    /**
     * Azure function which invoked by an by an EventHub trigger.
     * The Trigger is connected to a Notification Processor EventHub Topic.
     * This function receives the notification payload, checks the entity type and accordingly calls
     * the relevant processor
     */
    @FunctionName("NotificationProcessor")
    public void run(
            @EventHubTrigger(
                    name = Constants.TRIGGER_NAME,
                    eventHubName = Constants.TRIGGER_EVENT_HUB_NAME,
                    connection = Constants.TRIGGER_EVENT_HUB_CONNECTION_STRING_PROP,
                    consumerGroup = Constants.TRIGGER_EVENT_HUB_CONSUMER_GROUP,
                    cardinality = Cardinality.MANY
            ) List<String> messages,
            @BindingName(value = Constants.TRIGGER_SYSTEM_PROPERTIES_NAME) Map<String, Object>[] systemProperties,
            @BindingName(value = CommonConstants.PARTITION_CONTEXT) Map<String, Object> partitionContext,
            final ExecutionContext context) {
        JsonNode batchDetails = InvocationContext.getInvocationBatchInfo(partitionContext, systemProperties);
        try {
            InvocationContext.setupInvocationContext(context);
            notificationHandler.executeNotificationMessage(messages, systemProperties);
            InvocationContext.getLogger().log(Level.INFO, " Notification processed");
        } catch (Exception e) {
            // per message exception are handled in NotificationHandler, and are not bubbled up. Since the entire batch has failed,  capturing batch details
            ObjectNode identifiers = getIdentifiers(batchDetails);
            throw IoTRuntimeException.wrapTransient(identifiers,
                    CommonErrorType.RUNTIME_ERROR, "Error in processing the model change notification message batch", e);
        } finally {
            InvocationContext.closeInvocationContext();
        }
    }

    private ObjectNode getIdentifiers(JsonNode batchDetails) {
        ObjectNode identifier = objectMapper.createObjectNode();
        identifier.put(CommonConstants.PARTITION_ID, batchDetails.get(CommonConstants.PARTITION_ID).asText());
        identifier.put(CommonConstants.BATCH_OFFSET_START, batchDetails.get(CommonConstants.BATCH_OFFSET_START).asText());
        identifier.put(CommonConstants.BATCH_OFFSET_END, batchDetails.get(CommonConstants.BATCH_OFFSET_END).asText());
        return identifier;
    }
}
